### PR TITLE
(fix) onCandleUpdate return nextState instead of input state

### PR DESCRIPTION
**Pull request by Lecss**
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
This bug can be seen on using live data stream, with the bfx-hf-strategy-exec. When a new candle is received, upon processing the candle update message and a trade is executed, the state position object is overridden by the previous empty positions state; 

#### Steps to reproduce
-  run with bfx-hf-strategy-exec, place a trade from either onUpdate or onEnter. Position state is updated temporarily,  then on next candle_update it is reverted to empty object;

### CODE REVIEW

**Comment by JacobPlaster** [comment]
Hmmm @f3rno are you able to check this one out?

Thanks for raising the issue @Lecss

**Comment by JacobPlaster** [comment]
for reference: https://github.com/bitfinexcom/bfx-hf-strategy/issues/9

**Comment by f3rno** [comment]
lgtm, @Lecss can you bump the version & update the changelog as well? Then we can get this merged in. Nice fix :slightly_smiling_face:

**Comment by Lecss** [comment]
Great, version and changelog are now updated. I would suggest adding standard-version for automatically bumping version and updating changelog for these bfx repos. 

https://github.com/conventional-changelog/standard-version

**Pull request merged**
